/**
 * jsPDF Report Generation Service
 */

/**
 * Downloads a landscape master audit spreadsheet PDF for the active authority jurisdiction
 */
function downloadMasterPDF() {
  if (!masterPassList || masterPassList.length === 0) {
    return alert('No pass records found to export.');
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });

  doc.setFillColor(185, 28, 28);
  doc.rect(10, 10, 277, 24, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.text('GRT INSTITUTE OF ENGINEERING AND TECHNOLOGY, TIRUTTANI', 148, 18, { align: 'center' });

  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'normal');
  doc.text('(AN AUTONOMOUS INSTITUTION) • NAAC A++ • AICTE APPROVED • ANNA UNIVERSITY AFFILIATED', 148, 24, { align: 'center' });
  doc.text(
    `MASTER REPOSITORY AUDIT • JURISDICTION: ${loggedUser.role.toUpperCase()} (${loggedUser.dept || 'ALL'} ${loggedUser.yearSec ? '- Sec ' + loggedUser.yearSec : ''})`,
    148,
    30,
    { align: 'center' }
  );

  const nowString = new Date().toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
    dateStyle: 'full',
    timeStyle: 'medium'
  });
  doc.setTextColor(51, 65, 85);
  doc.setFontSize(8);
  doc.text(`Generated By: ${loggedUser.name} (${loggedUser.role.toUpperCase()}) | Date: ${nowString} IST`, 12, 39);

  const tableData = masterPassList.map((p, idx) => [
    idx + 1,
    p.rollNo,
    p.name,
    `${formatClassSection(p.dept, p.yearSec, p.academicYear)} [${loggedUser && (loggedUser.role === 'boys_warden' || loggedUser.role === 'girls_warden') ? 'Hosteller' : (/hostel/i.test(p.accommodation || '') ? 'Hosteller' : 'Day Scholar')}]`,
    p.appliedTime || '-',
    p.parentCallTime || '-',
    p.advisorApproval?.time || '-',
    p.hodApproval?.time || '-',
    p.approvalTime || '-',
    p.exitStatus === 'Exited Campus' ? `EXITED (${p.exitTime || ''})` : p.status
  ]);

  doc.autoTable({
    startY: 42,
    margin: { left: 10, right: 10 },
    head: [
      [
        '#',
        'Roll No',
        'Name',
        'Standing & Sec',
        '1. Applied (IST)',
        '2. Counselor (IST)',
        '3. Advisor (IST)',
        '4. HOD (IST)',
        '5. Principal (IST)',
        'Exit Status'
      ]
    ],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [185, 28, 28], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
    styles: { fontSize: 7, cellPadding: 2 }
  });

  doc.save(`GRTIET_Audit_Log_${loggedUser.role}_${Date.now()}.pdf`);
}

/**
 * Downloads a dossier of all official requisition letters in current jurisdiction
 */
function downloadAllCompleteLettersPDF() {
  if (!masterPassList || masterPassList.length === 0) {
    return alert('No requisition letters found to export.');
  }

  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  masterPassList.forEach((pass, index) => {
    if (index > 0) doc.addPage();

    doc.setDrawColor(203, 213, 225);
    doc.setLineWidth(0.6);
    doc.rect(10, 10, 190, 277);

    doc.setFillColor(185, 28, 28);
    doc.rect(10, 10, 190, 22, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('GRT INSTITUTE OF ENGINEERING AND TECHNOLOGY', 105, 18, { align: 'center' });
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.text('TIRUTTANI - 631 209 • (AN AUTONOMOUS INSTITUTION) • LEAVE REQUISITION DOSSIER', 105, 24, { align: 'center' });

    const letterText =
      pass.formalLetter ||
      `To The Principal,\n\nRespected Sir/Madam,\nI request leave due to: ${pass.reason}.\n\nYours obediently,\n${pass.name}`;

    doc.autoTable({
      startY: 36,
      margin: { left: 14, right: 14 },
      head: [[`OFFICIAL REQUISITION LETTER #${index + 1} • ROLL NO: ${pass.rollNo}`]],
      body: [[letterText]],
      theme: 'plain',
      headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8 },
      styles: { fontSize: 7.5, cellPadding: 3, font: 'courier', textColor: [30, 41, 59], lineHeight: 1.2 }
    });

    doc.autoTable({
      startY: doc.lastAutoTable.finalY + 4,
      margin: { left: 14, right: 14 },
      head: [['GOVERNANCE LEVEL', 'TIMESTAMP SIGN-OFF (IST) & STAMP']],
      body: [
        ['Student Submission Time', pass.appliedTime || '-'],
        ['Counselor Verification Time', pass.counselorApproval?.time || pass.parentCallTime || '-'],
        ['Class Advisor Approval Time', pass.advisorApproval?.time || '-'],
        ['HOD Authorization Time', pass.hodApproval?.time || '-'],
        ['Principal Clearance Time', pass.approvalTime || '-']
      ],
      theme: 'grid',
      headStyles: { fillColor: [185, 28, 28], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 7.5 },
      styles: { fontSize: 7.5, cellPadding: 2 }
    });

    const finalY = doc.lastAutoTable.finalY + 16;
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(71, 85, 105);

    doc.text('Class Counselor', 24, finalY);
    doc.text('Class Advisor', 72, finalY);
    doc.text('HOD', 122, finalY);
    doc.text('Principal / Security', 158, finalY);

    doc.setDrawColor(148, 163, 184);
    doc.line(20, finalY - 3, 50, finalY - 3);
    doc.line(68, finalY - 3, 98, finalY - 3);
    doc.line(118, finalY - 3, 140, finalY - 3);
    doc.line(155, finalY - 3, 192, finalY - 3);
  });

  doc.save(`GRTIET_All_Letters_${loggedUser.role}_${Date.now()}.pdf`);
}

/**
 * Downloads single official requisition letter PDF
 * @param {object} pass
 */
function downloadOfficialLetterOnlyPDF(pass) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.6);
  doc.rect(10, 10, 190, 277);

  doc.setFillColor(185, 28, 28);
  doc.rect(10, 10, 190, 22, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('GRT INSTITUTE OF ENGINEERING AND TECHNOLOGY', 105, 18, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('TIRUTTANI - 631 209 • (AN AUTONOMOUS INSTITUTION)', 105, 24, { align: 'center' });
  doc.text('FORMAL LEAVE & CAMPUS CLEARANCE APPLICATION REQUISITION', 105, 30, { align: 'center' });

  const letterText =
    pass.formalLetter ||
    `To The Principal,\n\nRespected Sir/Madam,\nI request leave due to: ${pass.reason}.\n\nYours obediently,\n${pass.name}`;

  doc.autoTable({
    startY: 36,
    margin: { left: 14, right: 14 },
    head: [['OFFICIAL REQUISITION LETTER']],
    body: [[letterText]],
    theme: 'plain',
    headStyles: { fillColor: [185, 28, 28], textColor: [255, 255, 255], fontStyle: 'bold', fontSize: 8.5 },
    styles: { fontSize: 8, cellPadding: 3, font: 'courier', textColor: [30, 41, 59], lineHeight: 1.25 }
  });

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 4,
    margin: { left: 14, right: 14 },
    head: [['CLEARANCE TIER', 'SIGN-OFF AUDIT TIMESTAMP (IST)']],
    body: [
      ['Application Submitted', pass.appliedTime || '-'],
      ['Counselor Parent Call Check', pass.counselorApproval?.time || pass.parentCallTime || '-'],
      ['Class Advisor Endorsement', pass.advisorApproval?.time || '-'],
      ['Head of Department Sign-off', pass.hodApproval?.time || '-'],
      ['Principal Clearance', pass.approvalTime || '-']
    ],
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 7.5, cellPadding: 2 }
  });

  const finalY = doc.lastAutoTable.finalY + 18;
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);

  doc.text('Class Counselor', 24, finalY);
  doc.text('Class Advisor', 72, finalY);
  doc.text('HOD', 122, finalY);
  doc.text('Principal / Directorate', 158, finalY);

  doc.setDrawColor(148, 163, 184);
  doc.line(20, finalY - 3, 50, finalY - 3);
  doc.line(68, finalY - 3, 98, finalY - 3);
  doc.line(118, finalY - 3, 140, finalY - 3);
  doc.line(155, finalY - 3, 192, finalY - 3);

  doc.save(`GRTIET_Letter_${pass.rollNo}.pdf`);
}

/**
 * Downloads official student pass slip PDF
 * @param {object} pass
 */
function downloadSinglePassPDF(pass) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });

  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.8);
  doc.rect(10, 10, 190, 277);

  doc.setFillColor(185, 28, 28);
  doc.rect(10, 10, 190, 25, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text('GRT INSTITUTE OF ENGINEERING AND TECHNOLOGY', 105, 18, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('TIRUTTANI - 631 209 • (AN AUTONOMOUS INSTITUTION)', 105, 24, { align: 'center' });
  doc.text('OFFICIAL CAMPUS GATE PASS & AUTHORIZED LEAVE CLEARANCE', 105, 30, { align: 'center' });

  doc.autoTable({
    startY: 40,
    margin: { left: 14, right: 14 },
    head: [['STUDENT PROFILE', 'OFFICIAL RECORD DETAILS']],
    body: [
      ['Roll Number', pass.rollNo || '-'],
      ['Student Name', pass.name || '-'],
      ['Academic Standing & Sec', formatClassSection(pass.dept, pass.yearSec, pass.academicYear)],
      ['Assigned Counselor', pass.counselorName || '-'],
      ['Verified Parent Phone', pass.parentContact || '-'],
      ['Student Mobile', pass.mobile || '-'],
      ['Applied Timestamp', pass.appliedTime || '-'],
      ['Stated Leave Reason', pass.reason || '-']
    ],
    theme: 'striped',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 8, cellPadding: 2.5 }
  });

  const governanceRows = [
    ['Tier 1: Counselor Parent Call Check', pass.counselorApproval?.time || pass.parentCallTime || 'Unverified'],
    ['Tier 2: Class Advisor Endorsement', pass.advisorApproval?.time || 'Pending'],
    ['Tier 3: HOD Authorization', pass.hodApproval?.time || 'Pending'],
    ['Tier 4: Principal Directorate Clearance', pass.principalApproval?.time || pass.approvalTime || 'Pending']
  ];

  if (/hostel/i.test(pass.accommodation || '')) {
    governanceRows.push([
      'Tier 5: Hostel Warden Clearance & Window',
      pass.wardenApproval?.approved
        ? `APPROVED • 20-Min Gate Pass (${pass.validUntil || pass.wardenApproval.time})`
        : 'Pending Warden'
    ]);
  }

  governanceRows.push([
    'Physical Campus Movement Status',
    pass.status === 'Returned' || pass.exitStatus === 'Returned to College'
      ? `RETURNED TO COLLEGE AT ${pass.returnTime} (Exited at ${pass.exitTime})`
      : pass.exitStatus === 'Exited Campus'
      ? `EXITED CAMPUS AT ${pass.exitTime}`
      : 'INSIDE CAMPUS'
  ]);

  doc.autoTable({
    startY: doc.lastAutoTable.finalY + 4,
    margin: { left: 14, right: 14 },
    head: [['GOVERNANCE LEVEL', 'TIMESTAMP SIGN-OFF (IST)']],
    body: governanceRows,
    theme: 'grid',
    headStyles: { fillColor: [30, 41, 59], textColor: [255, 255, 255], fontStyle: 'bold' },
    styles: { fontSize: 7.5, cellPadding: 2.5 }
  });

  const finalY = doc.lastAutoTable.finalY + 16;
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(71, 85, 105);

  doc.text('Class Counselor', 24, finalY);
  doc.text('Class Advisor', 72, finalY);
  doc.text('HOD', 122, finalY);
  doc.text('Principal / Security', 158, finalY);

  doc.setDrawColor(148, 163, 184);
  doc.line(20, finalY - 3, 50, finalY - 3);
  doc.line(68, finalY - 3, 98, finalY - 3);
  doc.line(118, finalY - 3, 140, finalY - 3);
  doc.line(155, finalY - 3, 192, finalY - 3);

  doc.save(`GRTIET_Pass_${pass.rollNo}.pdf`);
}
